[theme]
name = "TokyoNight"

[colors]
AlertInfo = "#8ce6ff"   # Light Blue
AlertWarn = "#e8bd76"   # Orange
AlertError = "#ef5f5f"  # Red
Annotation = "#e9e2f8"  # Light Periwinkle
Base = "#141021"        # Dark Blue
Guidance = "#ffab77"    # Coral
Important = "#c9aefc"   # Light Purple
Title = "#ff4fa3"       # Blue
