[theme]
name = "TokyoNight"

[colors]
AlertInfo = "#7dcfff"   # Light Blue
AlertWarn = "#e0af68"   # Orange
AlertError = "#db4b4b"  # Red
Annotation = "#ffd6ec"  # Light Periwinkle
Base = "#16111f"        # Dark Blue
Guidance = "#ff9e64"    # Coral
Important = "#bb9af7"   # Light Purple
Title = "#ff4fa3"       # Blue
