# Theme: tokyo-night
# By: Pascal Jaeger

# Main bg
theme[main_bg]="#141021"

# Main text color
theme[main_fg]="#e9e2f8"

# Title color for boxes
theme[title]="#e9e2f8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8ce6ff"

# Background color of selected item in processes box
theme[selected_bg]="#2c2246"

# Foreground color of selected item in processes box
theme[selected_fg]="#e9e2f8"

# Color of inactive/disabled text
theme[inactive_fg]="#9c8cc4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8ce6ff"

# Cpu box outline color
theme[cpu_box]="#9c8cc4"

# Memory/disks box outline color
theme[mem_box]="#9c8cc4"

# Net up/down box outline color
theme[net_box]="#9c8cc4"

# Processes box outline color
theme[proc_box]="#9c8cc4"

# Box divider line and small boxes line color
theme[div_line]="#9c8cc4"

# Temperature graph colors
theme[temp_start]="#a6dd70"
theme[temp_mid]="#e8bd76"
theme[temp_end]="#ff8fa3"

# CPU graph colors
theme[cpu_start]="#a6dd70"
theme[cpu_mid]="#e8bd76"
theme[cpu_end]="#ff8fa3"

# Mem/Disk free meter
theme[free_start]="#a6dd70"
theme[free_mid]="#e8bd76"
theme[free_end]="#ff8fa3"

# Mem/Disk cached meter
theme[cached_start]="#a6dd70"
theme[cached_mid]="#e8bd76"
theme[cached_end]="#ff8fa3"

# Mem/Disk available meter
theme[available_start]="#a6dd70"
theme[available_mid]="#e8bd76"
theme[available_end]="#ff8fa3"

# Mem/Disk used meter
theme[used_start]="#a6dd70"
theme[used_mid]="#e8bd76"
theme[used_end]="#ff8fa3"

# Download graph colors
theme[download_start]="#a6dd70"
theme[download_mid]="#e8bd76"
theme[download_end]="#ff8fa3"

# Upload graph colors
theme[upload_start]="#a6dd70"
theme[upload_mid]="#e8bd76"
theme[upload_end]="#ff8fa3"
