if [[ "$TERM_PROGRAM" == "ghostty" ]]; then
  export TERM=xterm-256color
fi

# --------------------------------------------------
# Source configuration files
# --------------------------------------------------
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/exports.zsh
source ~/.config/zsh/functions.zsh

# --------------------------------------------------
# PATH Management (Centralised + Deduplicated)
# --------------------------------------------------
typeset -U path PATH

# Base system paths
path=(
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
)

# Google Cloud SDK (eager PATH, lazy completions)
# The gcloud-cli cask symlinks gcloud/bq/gsutil straight into $HOMEBREW_PREFIX/bin,
# which is already on PATH — this line only covers a manual tarball install.
[[ -d "$HOME/google-cloud-sdk/bin" ]] && path+=("$HOME/google-cloud-sdk/bin")

# User tool paths
path+=(
  $HOME/.local/bin
  $HOME/.cargo/bin
  $HOME/.bun/bin
  $HOME/Library/pnpm
  $HOME/go/bin
  $HOME/vault/scripts
)

# --------------------------------------------------
# Completion Setup (Cached Daily)
# --------------------------------------------------
autoload -Uz compinit
setopt EXTENDEDGLOB

local zcompdump="$HOME/.zcompdump"

if [[ -n $zcompdump(#qNmh-24) ]]; then
  compinit -C -d "$zcompdump"
else
  compinit -d "$zcompdump"
fi

unsetopt EXTENDEDGLOB

# --------------------------------------------------
# Completion Styling
# --------------------------------------------------

# Case-insensitive + partial-word + substring matching
zstyle ':completion:*' matcher-list \
  'm:{a-z}={A-Z}' \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' \
  'l:|=* r:|=*'

# Group completions by type with descriptions
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '[%d]'

# Colored completions using LS_COLORS
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Include . and .. in directory completions
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' squeeze-slashes true

# Disable default menu — fzf-tab handles it
zstyle ':completion:*' menu no

# fzf-tab: directory previews
zstyle ':fzf-tab:complete:cd:*' fzf-preview \
  'eza --tree --level=2 --color=always $realpath 2>/dev/null'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview \
  'eza --tree --level=2 --color=always $realpath 2>/dev/null'

# fzf-tab: file previews
zstyle ':fzf-tab:complete:nvim:*' fzf-preview \
  'bat --color=always --style=numbers --line-range=:100 $realpath 2>/dev/null'

# fzf-tab: switch between completion groups with < and >
zstyle ':fzf-tab:*' switch-group '<' '>'

# --------------------------------------------------
# Plugins & Tools
# --------------------------------------------------

source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# fzf-tab is an upstream clone, not a brew formula — bootstrap it on a fresh machine
[[ -d ~/.config/zsh/fzf-tab ]] || \
  git clone -q --depth 1 https://github.com/Aloxaf/fzf-tab ~/.config/zsh/fzf-tab

# fzf-tab must load after compinit; use hook so zsh-vi-mode doesn't clobber its Tab binding
function zvm_after_init() {
  source ~/.config/zsh/fzf-tab/fzf-tab.plugin.zsh
}

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-syntax-highlighting/theme.zsh

export COREPACK_ENABLE_AUTO_PIN=0

# --------------------------------------------------
# Runtimes and tools (replaces nvm/asdf; see mise/config.toml)
# --------------------------------------------------
eval "$(mise activate zsh)"

# kubectl completions (cached — regenerate by deleting ~/.kubectl_zsh_completion)
# Must run after mise activate: kubectl is mise-managed, so the PATH built above
# does not contain it and the guard below would silently never fire.
if (( $+commands[kubectl] )); then
  local _kubectl_comp_cache="$HOME/.kubectl_zsh_completion"
  if [[ ! -f "$_kubectl_comp_cache" ]]; then
    kubectl completion zsh >! "$_kubectl_comp_cache" 2>/dev/null
  fi
  source "$_kubectl_comp_cache"
  compdef k=kubectl
  compdef kc=kubectl
fi

# nx completions. Generated by `nx completion zsh`, which appends to the rc file
# rather than writing to stdout — so it lands here, above zoxide, by hand.
###-begin-nx-completions-###
#
# nx command completion script
#
# Installation: nx completion zsh >> ~/.zshrc
#    or: nx completion zsh > /usr/local/share/zsh/site-functions/_nx
#
if type compdef &>/dev/null; then
  _nx_completions () {
    local reply nx_cmd dir
    local si=$IFS

    # Walk up for a workspace-local nx; fall back to PATH outside a workspace.
    nx_cmd="nx"
    dir="$PWD"
    while [[ "$dir" != "/" ]]; do
      if [[ -x "$dir/node_modules/.bin/nx" ]]; then
        nx_cmd="$dir/node_modules/.bin/nx"
        break
      fi
      if [[ -x "$dir/.nx/installation/node_modules/.bin/nx" ]]; then
        nx_cmd="$dir/.nx/installation/node_modules/.bin/nx"
        break
      fi
      dir="${dir:h}"
    done

    # Hide stderr so stray warnings don't land in the buffer; NX_VERBOSE_LOGGING surfaces it.
    if [[ -n "$NX_VERBOSE_LOGGING" ]]; then
      IFS=$'\n' reply=($(NX_COMPLETE=zsh "$nx_cmd" "${words[@]}"))
    else
      IFS=$'\n' reply=($(NX_COMPLETE=zsh "$nx_cmd" "${words[@]}" 2>/dev/null))
    fi
    IFS=$si

    # Split `value\tdescription` into parallel arrays for compadd -d. Don't
    # use _describe: it splits on ':', mangling values like `my-app:build`.
    local -a values displays
    local r value nospace=0
    for r in $reply; do
      value="${r%%$'\t'*}"
      values+=("$value")
      if [[ "$r" == *$'\t'* ]]; then
        displays+=("$value -- ${r#*$'\t'}")
      else
        displays+=("$value")
      fi
      [[ "$value" == *: ]] && nospace=1  # trailing ':' → nospace
    done

    if (( ${#values} == 0 )); then
      # Nothing to suggest — fall back to filename completion (covers
      # `nx g app --directory <TAB>` and similar unknown-flag values).
      _files
      return
    fi
    if (( nospace )); then
      compadd -S '' -d displays -a values
    else
      compadd -d displays -a values
    fi
  }
  compdef _nx_completions nx
else
  echo "nx: shell completion requires zsh's completion system to be loaded." >&2
  echo "    Add the following line to your ~/.zshrc above this block:" >&2
  echo "        autoload -U compinit && compinit" >&2
fi
###-end-nx-completions-###

# Alias completions. zsh resolves completion by the alias *name*, not what it
# expands to, so every shorthand needs its own mapping — `vim` picks up _vim for
# free but `v`/`vi`/`nv` do not. Guarded: compdef errors on a missing target.
# Deliberately outside the nx markers above so regenerating that block keeps nxr.
(( $+commands[nx] ))     && compdef nxr=nx
(( $+commands[nvim] ))   && compdef v=vim
(( $+commands[nvim] ))   && compdef vi=vim
(( $+commands[nvim] ))   && compdef nv=vim
(( $+commands[eza] ))    && compdef ls=eza
(( $+commands[eza] ))    && compdef ll=eza
(( $+commands[eza] ))    && compdef lt=eza
compdef pe=printenv

# --------------------------------------------------
# Per-project environment
# --------------------------------------------------
eval "$(direnv hook zsh)"

# --------------------------------------------------
# Lazy Load Google Cloud SDK (completions only, PATH set above)
# --------------------------------------------------
# Checks the gcloud-cli cask location first, then a manual tarball install.
lazy_load_gcloud_completions() {
  local inc
  for inc in \
    "${HOMEBREW_PREFIX:-/opt/homebrew}/share/google-cloud-sdk/completion.zsh.inc" \
    "$HOME/google-cloud-sdk/completion.zsh.inc"
  do
    [[ -f "$inc" ]] && { . "$inc"; return }
  done
}

gcloud() {
  unset -f gcloud gsutil
  lazy_load_gcloud_completions
  gcloud "$@"
}

gsutil() {
  unset -f gcloud gsutil
  lazy_load_gcloud_completions
  gsutil "$@"
}

# --------------------------------------------------
# Atuin
# --------------------------------------------------
eval "$(atuin init zsh)"

# --------------------------------------------------
# FZF Configuration
# --------------------------------------------------
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --height=80% \
  --preview-window=right:60% \
  --bind='ctrl-/:toggle-preview' \
  --bind='ctrl-u:preview-half-page-up' \
  --bind='ctrl-d:preview-half-page-down' \
  --color=bg+:#283457 \
  --color=bg:#16161e \
  --color=border:#27a1b9 \
  --color=fg:#c0caf5 \
  --color=gutter:#16161e \
  --color=header:#ff9e64 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#2ac3de \
  --color=query:#c0caf5:regular \
  --color=scrollbar:#27a1b9 \
  --color=separator:#ff9e64 \
  --color=spinner:#ff007c \
"

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'

export FZF_CTRL_T_OPTS="
  --preview 'bat --style=numbers --color=always --line-range :500 {}'
  --bind 'ctrl-/:toggle-preview'
"

export FZF_ALT_C_OPTS="
  --preview 'eza --tree --level=2 --color=always {} 2>/dev/null || ls -la {}'
"

# --------------------------------------------------
# Prompt + Navigation
# --------------------------------------------------
eval "$(starship init zsh)"

# --------------------------------------------------
# Bun
# --------------------------------------------------
export BUN_INSTALL="$HOME/.bun"
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# --------------------------------------------------
# pnpm
# --------------------------------------------------
# Cached — generating completions spawns pnpm on every shell start otherwise.
# Regenerate by deleting ~/.pnpm_zsh_completion
if (( $+commands[pnpm] )); then
  local _pnpm_comp_cache="$HOME/.pnpm_zsh_completion"
  if [[ ! -f "$_pnpm_comp_cache" ]]; then
    pnpm completion zsh >! "$_pnpm_comp_cache" 2>/dev/null
  fi
  source "$_pnpm_comp_cache"
fi

# --------------------------------------------------
# Local environment loader (if exists)
# --------------------------------------------------
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# --------------------------------------------------
# Zoxide (must be last)
# --------------------------------------------------
eval "$(zoxide init zsh)"
